- assets/css/fonts.css
Fixed this error when running `mix dev.storybook`
```
> phx_live_storybook@1.0.0 build:fonts_css
> tailwindcss --minify -i css/fonts.css -o ../priv/static/css/fonts.css
node:internal/process/promises:245
triggerUncaughtException(err, true /* fromPromise */);
^
Error: Unexpected '/'. Escaping special characters with \ may help.
at /Users/matthieuchabert/Documents/workspace/phx_live_storybook/assets/css/fonts.css:50:1
```
> Fixed TailwindCSS compilation crash caused by unescaped `/`

- lib/phx_live_storybook/live/sidebar.ex
This PR fixes the icon placement by adding a couple of classes which are also used for the folder icons.
Closes #118
> Fix user icon placement for StoryEntry in sidebar

- assets/tailwind.config.js
- lib/mix/tasks/phx.gen.storybook.ex
- priv/templates/phx.gen.storybook/icon.story.exs.eex
- priv/templates/phx.gen.storybook/my_component.story.exs.eex
- test/mix/tasks/phx.gen.storybook_test.exs
When I use `mix phx.gen.storybook` it crash when I go to `storybook/components/my_component`.
```
Request: GET /storybook/components/my_component
** (exit) an exception was raised:
** (Phoenix.LiveView.HTMLTokenizer.ParseError) nofile:1:12: expected attribute name
(phoenix_live_view 0.18.0) lib/phoenix_live_view/html_tokenizer.ex:339: Phoenix.LiveView.HTMLTokenizer.handle_attribute/5
(phoenix_live_view 0.18.0) lib/phoenix_live_view/html_engine.ex:231: Phoenix.LiveView.HTMLEngine.handle_text/3
(eex 1.14.0) lib/eex/compiler.ex:311: EEx.Compiler.generate_buffer/4
(phx_live_storybook 0.4.0) lib/phx_live_storybook/rendering/component_renderer.ex:261: PhxLiveStorybook.Rendering.ComponentRenderer.render_component_heex/3
(phx_live_storybook 0.4.0) lib/phx_live_storybook/live/story_live.ex:317: …
```
> Storybook generator fix

- lib/phx_live_storybook/router.ex
- test/phx_live_storybook/router_test.exs
- test/test_helper.exs
This adds a `session_name` option for the live session and an `as` option for the route helper name. I don't know how you would make it work with the `as` option passed to the surrounding scope.
There is one problem: The `storybook_browser` pipeline is defined any time `live_storybook` is called in the router. This leads to a warning:
```
warning: this clause for storybook_browser/2 cannot match because a previous clause at line 49 always matches
test/test_helper.exs:55
```
How do you want to solve this? Remove the pipeline from the macro and instruct users to add it manually?
resolves #126
> add :live_session and :as options

- assets/js/app.js
- guides/sandboxing.md
- guides/setup.md
- lib/phx_live_storybook/live/story_live.ex
- priv/templates/phx.gen.storybook/storybook.js
This allows a user to pass live socket connect parameters to page stories. I only need this for pages, not components. If someone needs this for components as well, we could change the `variations/0` to `variations/1`, but since that would be a breaking change and it's unclear whether anybody needs it, I wouldn't do that now.
resolves #129
> pass connect params to page story

- lib/phx_live_storybook/stories/index.ex
Fix the following dialyzer errors:
- Type mismatch for @callback folder_icon/0 in PhxLiveStorybook.Index.IndexBehaviour behaviour.
- Type mismatch for @callback folder_name/0 in PhxLiveStorybook.Index.IndexBehaviour behaviour.
- Type mismatch for @callback entry/1 in PhxLiveStorybook.Index.IndexBehaviour behaviour.
> Fix IndexBehaviour callback types

- lib/phx_live_storybook/stories/slot.ex
@cblavier I am not 100% sure about this, but we are using atom for `slot.id`. The same with any other id in variations, variation group, and attr. So I guess we should change the type to atom for slots as well.
This prevents the warning:
```
Warning: Type mismatch for @callback slots/0 in PhxLiveStorybook.Story.ComponentBehaviour behaviour
Expected type:
[
%PhxLiveStorybook.Stories.Slot{:doc => binary(), :id => binary(), :required => boolean()}
]
Actual type:
[%PhxLiveStorybook.Stories.Slot{:doc => <<_::72>>, :id => :tab, :required => false}, ...]
```
> Change Slot.id type from String to atom

- guides/sandboxing.md
- lib/phx_live_storybook/live/story/playground.ex
This removes the padding when using an iframe for sandboxing and improves the docs on it slightly.
> Do not inset iframe

- lib/phx_live_storybook/icon.ex
- lib/phx_live_storybook/stories/index.ex
- lib/phx_live_storybook/stories/story.ex
Our dialyzer was complaining that generated `navigation` doesn't match the `@callback`'s return type defined in behaviour.
I couldn't find the right place where would this icon `@type` definition fit best so created a module 🤷🏻‍♂️ 
please, let me know if there is a better place for this
> Fix @callback and reuse Icon's definition

- lib/phoenix_storybook/templates/layout/root.html.heex
Currently it is not possible to use javascript code that depends on certain DOM characteristics because the user's script tag is executed before the creation of the body.
By adding the `defer` attribute, the javascript file will be download along with the rendering of the document and executed after the document is rendered.
This allows the use case of using JS libraries that use the DOM characteristics in order to provide functionality, such as a script that selects rendered elements with `ripple="true"` and provide them this functionality.
> added "defer" attribute to application's js

- assets/js/app.js
- assets/js/iframe.js
- priv/templates/phx.gen.storybook/storybook.js
Currently, you can customize the LiveSocket configuration using `window.storybook.Hooks`, `window.storybook.Params`, and `window.storybook.Uploaders`; however, there's no way to set other options like `bindingPrefix` and `dom`.  Specifically, you need `dom` for components that use alpine.js.
This PR adds `window.storybook.LiveSocketOptions` as a generic way to pass options into LiveSocket configuration.
Additionally, I've updated the storybook.js template comments to explain how to use storybook with components that rely on alpine.js
I've tested this in my app with alpine.js. There are no breaking changes--if `LiveSocketOptions` is undefined, there is no change in functionality.
> Add LiveSocketOptions to support alpine.js

- lib/mix/tasks/phx.gen.storybook.ex
The `default` tailwind profile should already be there from the `mix phx.new`.  The generator has instructions to make a new `storybook` tailwind profile and that tailwind profile build command is what needs to be added to the `assets.deploy`
When I followed the instructions as printed when I did a release Phoenix was throwing a 404 on `/assets/storybook.css` because it wasn't being built.
> phx.gen.storybook alias to match storybook tailwind profile

- mix.exs
`config/config.exs` is the [default](https://hexdocs.pm/mix/1.12/Mix.Project.html#module-configuration).
Publishing the package with it specified but the path missing causes compilation (and potentially) other issues when pulling from hex.pm. 
closes: #335
> Use default `config_path` to allow compiling from hex.pm

- assets/package-lock.json
- lib/phoenix_storybook/mount.ex
- lib/phoenix_storybook/router.ex
- lib/phoenix_storybook/templates/layout/_favicon.html.heex
- lib/phoenix_storybook/templates/layout/live.html.heex
- lib/phoenix_storybook/templates/layout/root.html.heex
- lib/phoenix_storybook/templates/layout/root_iframe.html.heex
- lib/phoenix_storybook/views/layout_view.ex
Related to https://github.com/phenixdigital/phoenix_storybook/issues/149
To test this, add `csp_nonce_assign_key` to the `live_storybook` options, and add the function `put_csp/2` to the router of `phoenix_storybook_sample`. 
```elixir
scope "/", PhoenixStorybookSample do
pipe_through(:browser)
get "/", RedirectController, :redirect_to_storybook
live("/page", PageLive, :index)
live_storybook("/storybook",
backend_module: Storybook,
csp_nonce_assign_key: %{
img: :img_src_nonce,
style: :style_src_nonce,
script: :script_src_nonce
}
)
end
def put_csp(conn, _params) do
[img_nonce, style_nonce, script_nonce] =
for _i <- 1..3, do: 16 |> :crypto.strong_rand_bytes() |> Base.url_encode64(padding: false)
conn
|> assign(:img_src_nonce, img_nonce)
|> assign(:style_src_nonce, style_nonce)
|> …
```
> Fix CSP support

- lib/phoenix_storybook/live/story_live.ex
- test/fixtures/components/event_component.ex
- test/phoenix_storybook/live/story_live_test.exs
Since StoryLive is responsible for rendering components, any events from the components are sent to StoryLive. If handle_event is called for an unknown event, a FunctionClauseError will be raised, crashing the LiveView. This can be particularly problematic for any components that trigger an event on render.
This commit adds a catch all clause to handle_event/3
> No-op events unknown on StoryLive

- lib/phoenix_storybook/live/story_live.ex
Explicitly define the step for range with a negative index to get rid of the `negative steps are not supported in Enum.slice/2, pass 1..-1//1 instead` warning.
> Explicitly define step for range with negative index to get rid of warning

- lib/phoenix_storybook/rendering/component_renderer.ex
Solves #205  Before and after:
> nofile_error_due_to_missing_env

- lib/phoenix_storybook/helpers/validation_helpers.ex
- lib/phoenix_storybook/live/story/playground.ex
- lib/phoenix_storybook/stories/story_validator.ex
Tried to plug in `elixir 1.17.0-rc.0-otp-27` and had some compilation warnings. Here are some of the fixes.
> Fix Elixir 1.17 warnings

- lib/phoenix_storybook/exs_compiler.ex
Hi! Thanks for phoenix_storybook it's very cool.
We already set `:ignore_module_conflict` to `false` during tests to avoid these warning with gettext.
This fix avoid overriding this config.
Why do you need to edit this config in the first place?
> Restore original ignore_module_conflict compiler option

- README.md
- lib/phoenix_storybook.ex
- lib/phoenix_storybook/entries.ex
- lib/phoenix_storybook/exs_compiler.ex
- test/mix/tasks/phx.gen.storybook_test.exs
- test/phoenix_storybook/exs_compiler_test.exs
Closes #478
I had to make the `opts` available a bit deeper in the code, to read the `:compilation_debug` config option, but otherwise it seems to be a straightforward fix.
I am happy to adjust it based on your review or feel free to do it by yourself.
Thanks. :-)
> Add :compilation_debug config option

- CHANGELOG.md
- guides/components.md
- lib/phoenix_storybook/live/story_live.ex
- lib/phoenix_storybook/rendering/code_renderer.ex
- lib/phoenix_storybook/stories/story.ex
- lib/phoenix_storybook/stories/story_source.ex
- priv/templates/phx.gen.storybook/core_components/button.story.exs.eex
- priv/templates/phx.gen.storybook/core_components/flash.story.exs.eex
- priv/templates/phx.gen.storybook/core_components/header.story.exs.eex
- priv/templates/phx.gen.storybook/core_components/input.story.exs.eex
- priv/templates/phx.gen.storybook/core_components/list.story.exs.eex
- priv/templates/phx.gen.storybook/core_components/modal.story.exs.eex
- priv/templates/phx.gen.storybook/core_components/table.story.exs.eex
- test/fixtures/components/component.ex
- test/fixtures/storybook_content/tree/a_folder/component.story.exs
- test/fixtures/stubs/component_stub.ex
- test/fixtures/stubs/live_component_stub.ex
- test/phoenix_storybook/live/story_live_test.exs
- test/phoenix_storybook/stories/story_source_test.exs
- **story_source component_source only returns function source code for function components**
- **storybook renders function source code if opted in story**
- **generated core_component stories render only function source**
- **test warnings**
- **doc**
> Component stories can now render only function code

- lib/phoenix_storybook/live/story/playground.ex
Fixes #557 and also makes the HTML a bit nicer.
> Format HTML in the playground tab

- lib/phoenix_storybook/rendering/code_renderer.ex
- lib/phoenix_storybook/stories/doc.ex
- test/fixtures/components/component.ex
- test/phoenix_storybook/live/playground_live_test.exs
- test/phoenix_storybook/rendering/code_renderer_test.exs
- test/phoenix_storybook/stories/doc_test.exs
Hi @cblavier!
Finally I got some time work on Phoenix Storybook. 🙁 With this PR, I am building on your great work in #525 and fixing the only leftover from #514 – syntax highlighting for code blocks in the docs.
The code for highlighting was heavily inspired by
https://github.com/dashbitco/nimble_publisher/blob/140066e4c7b39f2c93bae662d3606fca1c1dce4d/lib/nimble_publisher/highlighter.ex
It works for both HEEx and Elixir code. When the language is not explicitly mentioned, HEEx is assumed if the code block starts with `<` (for an HTML tag), otherwise Elixir is used.
> Highlight code blocks in components docs

- guides/sandboxing.md
- lib/phoenix_storybook/templates/layout/root.html.heex
- lib/phoenix_storybook/templates/layout/root_iframe.html.heex
- lib/phoenix_storybook/views/layout_view.ex
We are using unbundled JavaScript without a build process, using ESM-style imports in the process. This requires the `script` tag to have `type="module"` added.
This PR adds a new configuration option, `js_script_type`, that defaults to `text/javascript` - which was the previous default. In our case, we can set it to `module` to support our scripts.
In addition, in Storybook's case, Storybook's own assets need to be loaded after, so I added the `defer` tag.
> Support ESM imports for scripts

- lib/phoenix_storybook/helpers/example_helpers.ex
- lib/phoenix_storybook/live/story_live.ex
- test/phoenix_storybook/helpers/example_helpers_test.exs
Hi @cblavier! I am creating a PR as I promised.
---
Altering code via regex is very hard and therefore the regexes for stripping `doc` and `extra_sources` functions were not very robust and were stripping wrong pieces of the source code.
I am replacing them with transformation on the AST level. It should be much more robust and hopefully still maintain much of the original formatting (given the original source code was formatted).
Fixes #605
> Improve example source code stripping

- lib/phoenix_storybook/templates/layout/root.html.heex
I was investigating why Firefox didn't reload my CSS styles after changing them anymore, and only in the Storybook. Found this instead.
> fix: remove stray curly brace

- lib/phoenix_storybook/stories/index.ex
The default implementation of `folder_index/0` returns `nil`:
https://github.com/phenixdigital/phoenix_storybook/blob/f9e98e93d07e89f7edaee9eb4682ef98c95185a4/lib/phoenix_storybook/stories/index.ex#L66
Which results in a Dialyzer warning in applications using storybook:
```
storybook/_root.index.exs:5:callback_type_mismatch
Type mismatch for @callback folder_index/0 in PhoenixStorybook.Index.IndexBehaviour behaviour.
Expected type:
integer()
Actual type:
nil
```
> fix: folder_index callback spec
